# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Workruta' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Workruta
  pod 'GooglePlaces', '6.2.1'
  pod 'Mantis', '~> 1.9.0'
  pod 'Alamofire'
  pod 'Stripe'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
